package umg.pojos;
// Generated 09-nov-2017 21:45:51 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Checkout generated by hbm2java
 */
public class Checkout  implements java.io.Serializable {


     private BigDecimal idcheckout;
     private Reserva reserva;

    public Checkout() {
    }

	
    public Checkout(BigDecimal idcheckout) {
        this.idcheckout = idcheckout;
    }
    public Checkout(BigDecimal idcheckout, Reserva reserva) {
       this.idcheckout = idcheckout;
       this.reserva = reserva;
    }
   
    public BigDecimal getIdcheckout() {
        return this.idcheckout;
    }
    
    public void setIdcheckout(BigDecimal idcheckout) {
        this.idcheckout = idcheckout;
    }
    public Reserva getReserva() {
        return this.reserva;
    }
    
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }




}


