package umg.pojos;
// Generated 09-nov-2017 21:45:51 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Checkin generated by hbm2java
 */
public class Checkin  implements java.io.Serializable {


     private BigDecimal idcheckin;
     private Cliente cliente;
     private Date fecha;
     private Date fechasalida;
     private Set reservas = new HashSet(0);

    public Checkin() {
    }

	
    public Checkin(BigDecimal idcheckin) {
        this.idcheckin = idcheckin;
    }
    public Checkin(BigDecimal idcheckin, Cliente cliente, Date fecha, Date fechasalida, Set reservas) {
       this.idcheckin = idcheckin;
       this.cliente = cliente;
       this.fecha = fecha;
       this.fechasalida = fechasalida;
       this.reservas = reservas;
    }
   
    public BigDecimal getIdcheckin() {
        return this.idcheckin;
    }
    
    public void setIdcheckin(BigDecimal idcheckin) {
        this.idcheckin = idcheckin;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getFechasalida() {
        return this.fechasalida;
    }
    
    public void setFechasalida(Date fechasalida) {
        this.fechasalida = fechasalida;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


