package umg.pojos;
// Generated 09-nov-2017 21:45:51 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private BigDecimal idcliente;
     private BigDecimal dpi;
     private String nombrecompleto;
     private BigDecimal telefono;
     private String codigotributario;
     private String correoelectronico;
     private String nacionalidad;
     private Set checkins = new HashSet(0);
     private Set reservas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(BigDecimal idcliente) {
        this.idcliente = idcliente;
    }
    public Cliente(BigDecimal idcliente, BigDecimal dpi, String nombrecompleto, BigDecimal telefono, String codigotributario, String correoelectronico, String nacionalidad, Set checkins, Set reservas) {
       this.idcliente = idcliente;
       this.dpi = dpi;
       this.nombrecompleto = nombrecompleto;
       this.telefono = telefono;
       this.codigotributario = codigotributario;
       this.correoelectronico = correoelectronico;
       this.nacionalidad = nacionalidad;
       this.checkins = checkins;
       this.reservas = reservas;
    }
   
    public BigDecimal getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(BigDecimal idcliente) {
        this.idcliente = idcliente;
    }
    public BigDecimal getDpi() {
        return this.dpi;
    }
    
    public void setDpi(BigDecimal dpi) {
        this.dpi = dpi;
    }
    public String getNombrecompleto() {
        return this.nombrecompleto;
    }
    
    public void setNombrecompleto(String nombrecompleto) {
        this.nombrecompleto = nombrecompleto;
    }
    public BigDecimal getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(BigDecimal telefono) {
        this.telefono = telefono;
    }
    public String getCodigotributario() {
        return this.codigotributario;
    }
    
    public void setCodigotributario(String codigotributario) {
        this.codigotributario = codigotributario;
    }
    public String getCorreoelectronico() {
        return this.correoelectronico;
    }
    
    public void setCorreoelectronico(String correoelectronico) {
        this.correoelectronico = correoelectronico;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public Set getCheckins() {
        return this.checkins;
    }
    
    public void setCheckins(Set checkins) {
        this.checkins = checkins;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


