package umg.pojos;
// Generated 09-nov-2017 21:45:51 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Habitacion generated by hbm2java
 */
public class Habitacion  implements java.io.Serializable {


     private BigDecimal idhabitacion;
     private Hotel hotel;
     private String tipo;
     private BigDecimal precio;
     private String imagen;
     private Set reservas = new HashSet(0);

    public Habitacion() {
    }

	
    public Habitacion(BigDecimal idhabitacion) {
        this.idhabitacion = idhabitacion;
    }
    public Habitacion(BigDecimal idhabitacion, Hotel hotel, String tipo, BigDecimal precio, String imagen, Set reservas) {
       this.idhabitacion = idhabitacion;
       this.hotel = hotel;
       this.tipo = tipo;
       this.precio = precio;
       this.imagen = imagen;
       this.reservas = reservas;
    }
   
    public BigDecimal getIdhabitacion() {
        return this.idhabitacion;
    }
    
    public void setIdhabitacion(BigDecimal idhabitacion) {
        this.idhabitacion = idhabitacion;
    }
    public Hotel getHotel() {
        return this.hotel;
    }
    
    public void setHotel(Hotel hotel) {
        this.hotel = hotel;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


