package umg.pojos;
// Generated 09-nov-2017 21:45:51 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private BigDecimal idreserva;
     private Cliente cliente;
     private Habitacion habitacion;
     private Checkin checkin;
     private String estado;
     private Date fechareserva;
     private String observacion;
     private Set checkouts = new HashSet(0);

    public Reserva() {
    }

	
    public Reserva(BigDecimal idreserva) {
        this.idreserva = idreserva;
    }
    public Reserva(BigDecimal idreserva, Cliente cliente, Habitacion habitacion, Checkin checkin, String estado, Date fechareserva, String observacion, Set checkouts) {
       this.idreserva = idreserva;
       this.cliente = cliente;
       this.habitacion = habitacion;
       this.checkin = checkin;
       this.estado = estado;
       this.fechareserva = fechareserva;
       this.observacion = observacion;
       this.checkouts = checkouts;
    }
   
    public BigDecimal getIdreserva() {
        return this.idreserva;
    }
    
    public void setIdreserva(BigDecimal idreserva) {
        this.idreserva = idreserva;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Habitacion getHabitacion() {
        return this.habitacion;
    }
    
    public void setHabitacion(Habitacion habitacion) {
        this.habitacion = habitacion;
    }
    public Checkin getCheckin() {
        return this.checkin;
    }
    
    public void setCheckin(Checkin checkin) {
        this.checkin = checkin;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFechareserva() {
        return this.fechareserva;
    }
    
    public void setFechareserva(Date fechareserva) {
        this.fechareserva = fechareserva;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Set getCheckouts() {
        return this.checkouts;
    }
    
    public void setCheckouts(Set checkouts) {
        this.checkouts = checkouts;
    }




}


