package umg.pojos;
// Generated 09-nov-2017 21:45:51 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private BigDecimal idusuario;
     private String usuario;
     private String contrasena;
     private String nombrecompleto;
     private String correoelectronico;
     private String puesto;

    public Usuario() {
    }

	
    public Usuario(BigDecimal idusuario) {
        this.idusuario = idusuario;
    }
    public Usuario(BigDecimal idusuario, String usuario, String contrasena, String nombrecompleto, String correoelectronico, String puesto) {
       this.idusuario = idusuario;
       this.usuario = usuario;
       this.contrasena = contrasena;
       this.nombrecompleto = nombrecompleto;
       this.correoelectronico = correoelectronico;
       this.puesto = puesto;
    }
   
    public BigDecimal getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(BigDecimal idusuario) {
        this.idusuario = idusuario;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getNombrecompleto() {
        return this.nombrecompleto;
    }
    
    public void setNombrecompleto(String nombrecompleto) {
        this.nombrecompleto = nombrecompleto;
    }
    public String getCorreoelectronico() {
        return this.correoelectronico;
    }
    
    public void setCorreoelectronico(String correoelectronico) {
        this.correoelectronico = correoelectronico;
    }
    public String getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }




}


